import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { domAnimation, LazyMotion } from "motion/react";
import Header from "@/components/Header";

const poppins = Poppins({
  subsets: ["latin"], // Choose language subsets as needed
  weight: ["200", "300", "400", "500", "700"], // Include only the weights you use
  variable: "--font-poppins", // Optional CSS variable
  preload: true, // Ensures the font is preloaded automatically
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}  antialiased`}>
        <LazyMotion features={domAnimation}>
          <Header />
          <main className="">{children}</main>
          <div id="modal-root"></div>
        </LazyMotion>
      </body>
    </html>
  );
}
