
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import InnerLayout from "@/components/InnerLayout";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
  subsets: ["latin"], // Choose language subsets as needed
  weight: ["200", "300", "400", "500", "700"], // Include only the weights you use
  variable: "--font-poppins", // Optional CSS variable
  preload: true, // Ensures the font is preloaded automatically
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full" lang="en">
      <body className={`${poppins.className} flex min-h-full flex-col antialiased`}>
       <InnerLayout>
        {children}
        <Toaster/>
       </InnerLayout>
      </body>
    </html>
  );
}
